# Generated by Django 4.2 on 2023-04-13 17:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Comedy", "Comedy"),
                            ("Action", "Action"),
                            ("Horror", "Horror"),
                            ("Fantasy", "Fantasy"),
                            ("Romance", "Romance"),
                            ("Drama", "Drama"),
                            ("SciFi", "SciFi"),
                            ("Documentary", "Documentary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_uploaded", models.DateField()),
                ("actors", models.ManyToManyField(to="movie.actor")),
            ],
        ),
    ]
